name: PR Build check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync
          git submodule update --init --force

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag libass/javascriptsubtitlesoctopus:latest

      - name: Build All
        run: docker run --rm -v ${PWD}:/code libass/javascriptsubtitlesoctopus:latest
      
      - uses: actions/upload-artifact@v1
        with:
          name: js
          path: dist/js